const HERO_IMAGE_STATE = { url: "https://historyreclaimed.co.uk/wp-content/uploads/2022/11/T06856_10.jpg" };

function applyHeroImage() { const hero = document.querySelector(".hero");
if (!hero) return;
if (HERO_IMAGE_STATE.url && HERO_IMAGE_STATE.url.trim().length > 0) { hero.style.setProperty("--hero-bg-image", `url("${HERO_IMAGE_STATE.url}")`);} 
else { hero.style.setProperty("--hero-bg-image", "none"); } }

function setHeroImage(url) { HERO_IMAGE_STATE.url = url; applyHeroImage(); }
window.setHeroImage = setHeroImage;

const LOOT_ITEMS =
[ { "name": "The Koh-i-Noor Diamond",
"category": "Jewels & Royal Regalia",
"origin": "Golconda mines, present-day Andhra Pradesh",
"period": "Mughal era, mined centuries earlier",
"taken": "1849, Treaty of Lahore",
"location": "Tower of London (Royal Collection)",
"status": "Still in Britain",
"image": "https://images.hindustantimes.com/rf/image_size_640x362/HT/p2/2016/04/19/Pictures/_35a0677a-05dd-11e6-afce-cd590874c67e.jpg",
"summary": "The world's most infamous diamond, surrendered by a ten-year-old maharaja.",
"history": "Passed through Mughal, Persian, Afghan and Sikh hands for centuries before the ten-year-old Maharaja Duleep Singh was made to surrender it to the East India Company after the annexation of Punjab. It was presented to Queen Victoria and later set into the crown worn at royal coronations. India, Pakistan, Iran and Afghanistan have all formally asked for it back.",
"marquee": true,
"id": "the-koh-i-noor-diamond" },

{ "name": "The Timur Ruby",
"category": "Jewels & Royal Regalia",
"origin": "Mughal treasury, Delhi",
"period": "Inscribed by five Mughal emperors from Jahangir onward",
"taken": "1849, seized with the Lahore treasury",
"location": "Royal Collection Trust, London",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzRBoB3wRY400U6z9K_n0DU_rH_yEzAgWnYmnoyGzjYwy2pfDHVh1VZKk&s=10",
"summary": "Not a ruby at all but a 361-carat spinel, engraved with the names of the Mughal emperors who once owned it.",
"history": "It left India in the same shipment as the Koh-i-Noor, folded quietly into the same act of confiscation, and has been worn by British royals ever since in a necklace made especially to hold it.",
"marquee": true,
"id": "the-timur-ruby" },

{ "name": "Lahore Toshakhana Jewels",
"category": "Jewels & Royal Regalia",
 "origin": "Sikh Empire treasury, Lahore",
"period": "Early 19th century",
"taken": "1849, annexation of Punjab",
"location": "Dispersed, UK museums and private collections",
"status": "Still in Britain",
"image": "blob:https://gemini.google.com/3da57d77-9d02-490c-ae8c-eba560d9659c",
"summary": "The royal treasury of the Sikh Empire, inventoried and divided up as war booty.",
"history": "Maharaja Ranjit Singh's Toshakhana held one of the richest jewel collections in Asia. After annexation, British officials catalogued and dispersed it — the finest pieces to London, the rest sold at auction to fund the occupying administration.",
"marquee": false,
"id": "lahore-toshakhana-jewels" },

{ "name": "Ranjit Singh's Pearl and Emerald Necklace",
"category": "Jewels & Royal Regalia",
"origin": "Lahore, Sikh Empire",
"period": "c. 1830s",
"taken": "1849",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://www.bonhams.com/_next/image.jpg?url=https%3A%2F%2Fimg1.bonhams.com%2Fimage%3Fsrc%3DImages%2Flive%2F2018-08%2F16%2F94624436-1-7.jpg&w=2400&q=75",
"summary": "Court jewellery worn by the Sikh royal family on state occasions.",
"history": "Seized alongside the Koh-i-Noor and Timur Ruby, this necklace was never singled out for a royal collection and instead disappeared into the private art market, changing hands quietly for over a century.",
"marquee": false,
"id": "ranjit-singh-s-pearl-and-emerald-necklace" },

{ "name": "Nizam's Court Diamond Set",
    "category": "Jewels & Royal Regalia",
    "origin": "Hyderabad, Deccan",
    "period": "18th-19th century",
    "taken": "Colonial-era acquisition",
    "location": "Dispersed, UK and Europe",
    "status": "Disputed",
    "image": "https://thediamondtalk.in/wp-content/uploads/2020/06/taveez-necklace.jpg",
    "summary": "Diamonds and gem-set jewellery of the kind worn at the Hyderabad Deccan court.",
    "history": "The Deccan sultanates and later Hyderabad state were renowned for diamond wealth. Company officials acquired court jewellery through both forced 'gifting' and outright confiscation as political control tightened.",
    "marquee": false,
    "id": "nizam-s-court-diamond-set" },

{ "name": "Golden Armlet of a Maratha Peshwa",
"category": "Jewels & Royal Regalia",
"origin": "Pune, Maratha Empire",
"period": "18th century",
"taken": "1818, after the Third Anglo-Maratha War",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://m.media-amazon.com/images/I/41hxppS2mTL._AC_UY1100_.jpg",
"summary": "A gem-set gold armlet in the Maratha court style, taken when the Peshwa's capital fell.",
"history": "When Pune fell in 1818, the Peshwa's treasury was seized in full. Ornaments of this kind were formally distributed among officers as prize money under East India Company regulations.",
"marquee": false,
"id": "golden-armlet-of-a-maratha-peshwa" },

{ "name": "Tipu Sultan's Sword",
"category": "Weapons & Armour",
"origin": "Seringapatam, Mysore",
"period": "Late 18th century",
"taken": "1799, fall of Seringapatam",
"location": "Returned to India, 2004 (private collection)",
"status": "Returned",
"image": "https://m.economictimes.com/thumb/msid-100555334,width-1200,height-1200,resizemode-4,imgsize-193564/tipu-sultans-bedchamber-sword-creates-new-auction-record-in-uk.jpg",
"summary": "The personal sword of the 'Tiger of Mysore', taken from his body on the day he died.",
"history": "Tipu Sultan was killed defending his capital in 1799 and his sword was carried off as trophy. It remained in Britain for two centuries until businessman Vijay Mallya bought it at a London auction in 2004 for over Rs 1.5 crore and brought it home — one of the rare items on this ledger with 'Returned' beside its name.",
"marquee": true,
"id": "tipu-sultan-s-sword" },

{ "name": "Tipu Sultan's Mechanical Tiger",
"category": "Weapons & Armour",
"origin": "Seringapatam, Mysore",
"period": "c. 1793",
"taken": "1799, fall of Seringapatam",
"location": "Victoria and Albert Museum, London",
"status": "Still in Britain",
"image": "https://smarthistory.org/wp-content/uploads/2017/08/tiger-whole.jpg",
"summary": "A life-sized wooden automaton of a tiger mauling a British soldier, with a hidden organ that makes both figures cry out.",
"history": "Built for a ruler whose hatred of the East India Company was legendary, the automaton's hand-cranked organ raises the soldier's arm while both figures groan. Tipu's treasury was divided on the spot among the soldiers by rank, but the tiger was shipped whole to London, where it has stayed on display ever since.",
"marquee": true,
"id": "tipu-sultan-s-mechanical-tiger" },

{ "name": "Tipu Sultan's Ring",
"category": "Weapons & Armour",
"origin": "Seringapatam, Mysore",
"period": "Late 18th century",
"taken": "1799",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://news.bbcimg.co.uk/media/images/75044000/jpg/_75044701_75044700.jpg",
"summary": "A gold ring inscribed in Devanagari script, taken from Tipu Sultan after his death.",
"history": "The ring surfaced at a London auction generations later, its Devanagari inscription complicating simple narratives about its owner. It remains in private British hands to this day.",
"marquee": false,
"id": "tipu-sultan-s-ring" },

{
"name": "Tipu Sultan's Bedchamber Dagger",
"category": "Weapons & Armour",
"origin": "Seringapatam, Mysore",
"period": "Late 18th century",
"taken": "1799",
"location": "Clive Museum, Powis Castle, Wales",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIfqcEf9Thy-Ag3JetHIBy-ZLwDyY9boWMndQT6E0o4BvlvExGQDPKTcd4&s=10",
"summary": "A jewelled dagger taken from Tipu Sultan's personal chambers.",
"history": "It entered the collection of Lord Clive's family, who took a substantial private share of the Seringapatam treasury as senior officers of the campaign against Mysore.",
"marquee": false,
"id": "tipu-sultan-s-bedchamber-dagger" },

{ "name": "Wellesley Collection Sabre",
"category": "Weapons & Armour",
"origin": "Seringapatam, Mysore",
"period": "Late 18th century",
"taken": "1799",
"location": "Private and museum collections, UK",
"status": "Still in Britain",
"image": "https://collection.nam.ac.uk/images/960/272000-272999/272894.jpg",
"summary": "A curved sabre from the Seringapatam armoury, part of the Wellesley family's share of the spoils.",
"history": "Richard Wellesley, Governor-General during the campaign, and his brother Arthur, the future Duke of Wellington, both took weapons from Tipu's treasury. Several pieces remain in British family collections today.",
"marquee": false,
"id": "wellesley-collection-sabre" },

{ "name": "Sikh Khanda (Ceremonial Sword)",
"category": "Weapons & Armour",
"origin": "Lahore, Punjab",
"period": "Early 19th century",
"taken": "1849, annexation of Punjab",
"location": "Museum collection, UK",
"status": "Still in Britain",
"image": "https://shreeamritsarsword.com/wp-content/uploads/2020/04/Khanda-min.jpg",
"summary": "A straight double-edged sword, sacred to the Khalsa, taken after the Anglo-Sikh Wars.",
"history": "The khanda held deep religious meaning for the Sikh Khalsa. Ceremonial and battle swords from the Lahore armoury were confiscated wholesale after annexation and later scattered across regimental and private British collections.",
"marquee": false,
"id": "sikh-khanda-ceremonial-sword" },

{ "name": "Maratha Firangi Sword",
"category": "Weapons & Armour",
"origin": "Maharashtra",
"period": "18th century",
"taken": "1818, collapse of the Maratha Confederacy",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Mumtaz_Mahal_Museum%2C_Red_Fort_-_Firangi.jpg/250px-Mumtaz_Mahal_Museum%2C_Red_Fort_-_Firangi.jpg",
"summary": "A basket-hilted sword with a European-style blade, favoured by Maratha cavalry.",
 "history": "The firangi, literally 'foreigner', paired an imported blade with an Indian hilt. Weapons of this class were taken in large numbers from Maratha armouries after the Third Anglo-Maratha War.",
"marquee": false,
"id": "maratha-firangi-sword" },
{
"name": "Rajput Talwar, Gold-Damascened Hilt",
"category": "Weapons & Armour",
"origin": "Rajasthan",
"period": "18th century",
"taken": "Colonial-era acquisition",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS40M3sHXAirzRo4nBojw6aa86G3wi6BJhGePqvRG92rfvk54XD88jyA6le&s=10",
"summary": "A curved sabre with a gold-inlaid hilt, as much a court presentation piece as a battlefield weapon.",
"history": "Weapons of this quality left princely armouries through purchase under duress, forced gifting, or outright seizure as British paramountcy tightened its grip on Rajasthan's courts.",
"marquee": false,
"id": "rajput-talwar-gold-damascened-hilt" },

{ "name": "Mysore Bubri-Pattern Dagger",
"category": "Weapons & Armour",
"origin": "Seringapatam, Mysore",
"period": "Late 18th century",
"taken": "1799",
"location": "Victoria and Albert Museum, London",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG9qOt18W5s1s4pmShxVEsfTpvtyipHRAUpRksZbtYpIN37wh3wQYQlj0&s=10",
"summary": "A dagger bearing Tipu Sultan's signature tiger-stripe motif.",
"history": "The bubri pattern appeared across Tipu's weapons, armour and throne fittings as a personal emblem of resistance. Pieces bearing it were prized trophies for officers after Seringapatam fell.",
"marquee": false,
"id": "mysore-bubri-pattern-dagger" },

{ "name": "Awadh Court Sword of a Nawab",
"category": "Weapons & Armour",
"origin": "Lucknow, Awadh",
"period": "19th century",
"taken": "1856, annexation of Awadh",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmGlVz_GZkuqJeWYu7k0p2YsJin-YJbAyHpjKmNc5M8XxgI2R_hfCKMxe&s=10",
"summary": "A ceremonial sword from the Nawabi court of Lucknow.",
"history": "Awadh's annexation, carried out on the pretext of misgovernance, saw the Nawab's armoury and treasury dispersed. Ceremonial weapons of this kind passed quietly into British private hands.",
"marquee": false,
"id": "awadh-court-sword-of-a-nawab" },

{ "name": "Sikh Khalsa Chain Mail",
"category": "Weapons & Armour",
"origin": "Punjab",
"period": "Early 19th century",
"taken": "1849",
"location": "Museum collection, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXlKPU2ENth1JP7XieBuuOgMVJhQwOAf1wlBbYeuEvEyiB8ZpwW_m0yXk&s=10",
"summary": "A full chain-and-plate mail coat worn by Sikh Khalsa heavy cavalry.",
"history": "Confiscated Sikh armouries supplied British collections with large quantities of arms and armour after the Anglo-Sikh Wars, most of it never inventoried for eventual return.",
"marquee": false,
"id": "sikh-khalsa-chain-mail" },

{ "name": "Rajput Steel Shield (Dhal)",
"category": "Weapons & Armour",
"origin": "Rajasthan",
"period": "18th century",
"taken": "Colonial-era acquisition",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://web.prm.ox.ac.uk/weapons/images/joomgallery/originals/asia_3/arms_and_armour_-_asia_20101126_1184016600.jpg",
"summary": "A round steel shield with gold koftgari inlay work.",
"history": "Shields like this were both functional armour and status objects, displayed rather than only carried. Many entered the colonial arms trade as princely states were absorbed into British paramountcy.",
"marquee": false,
"id": "rajput-steel-shield-dhal" },
{ "name": "Maratha Helmet (Top)",
"category": "Weapons & Armour",
"origin": "Maharashtra",
"period": "18th century",
"taken": "1818",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1Ij6SvAhARNtSOhEGgV03eNmjCUMq1tIY-Cd-H8N0Fgh6YQwDOyjLIkQ&s=10",
"summary": "A conical steel helmet with a chain-mail neck guard, worn by Maratha cavalry officers.",
"history": "Following the Third Anglo-Maratha War, arms and armour from Maratha arsenals were widely dispersed among British collectors as personal souvenirs of the campaign.",
"marquee": false,
"id": "maratha-helmet-top" },

{ "name": "Deccani Katar (Push-Dagger)",
"category": "Weapons & Armour",
"origin": "Deccan",
"period": "17th-18th century",
"taken": "Colonial-era acquisition",
"location": "Museum storage, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwNka0PKm90N3BaPfxcTQD2xE3yYq_I9RH7dMW30Kunq-tDe7_X6NGXpGk&s=10",
"summary": "An H-shaped push-dagger unique to the Indian subcontinent, richly decorated in Deccan style.",
"history": "Fine examples of this distinctly Indian weapon form entered British collections through the arms trade that flourished around colonial military campaigns and 'Oriental arms' exhibitions in Victorian London.",
"marquee": false,
"id": "deccani-katar-push-dagger" },

{ "name": "Sikh Chakram Set (Throwing Quoits)",
"category": "Weapons & Armour",
"origin": "Punjab",
"period": "Early 19th century",
"taken": "1849",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD_ZRC4aFW1ZFVVlPPCt8DD16fH-ElfR-4_oqGgP6dQfbyZbd3ps1taRg&s=10",
"summary": "A set of sharpened iron throwing rings, worn on the turbans of Akali Nihang warriors.",
"history": "Taken from Khalsa armouries after annexation, sets like this became popular curiosities in Victorian drawing rooms, valued more for their strangeness than their meaning.",
"marquee": false,
"id": "sikh-chakram-set-throwing-quoits" },

{ "name": "Mughal Cuirass (Body Armour)",
"category": "Weapons & Armour",
"origin": "North India",
"period": "17th-18th century",
"taken": "Colonial-era acquisition",
"location": "Museum storage, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRGRXuZ1bQ8UeHBzBrMzt8TJCS90lHMv5x9pFu5hnFX7lMr-jnrAIYx7Uw&s=10",
"summary": "A steel breastplate in the Mughal military style, worn by high-ranking officers.",
"history": "Armour of this kind circulated widely across successor states and was a frequent target for colonial-era collectors assembling military museum displays of 'Oriental' arms.",
"marquee": false,
"id": "mughal-cuirass-body-armour" },

{ "name": "Elephant War-Armour Panel (Bakhtar)",
"category": "Weapons & Armour",
"origin": "North India",
"period": "18th century",
"taken": "Colonial-era acquisition",
"location": "Museum collection, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGzZNpVvStuSpdYi-uaCG_Xy2_7em0Nt_z3_qS8-6VQaIQsgmu4rJg3Z8w&s=10",
"summary": "A steel plate from a suit of war-elephant armour.",
"history": "War elephants in Mughal successor-state armies were sometimes armoured for battle. Surviving panels were treated as exceptional curiosities and actively sought by British military museums.",
"marquee": false,
"id": "elephant-war-armour-panel-bakhtar" },

{ "name": "Maratha Bichwa (Scorpion Dagger)",
"category": "Weapons & Armour",
"origin": "Maharashtra",
"period": "18th century",
"taken": "Colonial-era acquisition",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Indian_bichwa_dagger.jpg",
"summary": "A curved dagger shaped like a scorpion's sting, concealed easily by Maratha light cavalry.",
"history": "Compact weapons like the bichwa were common across Maratha armies and were taken in numbers as curiosities by British officers serving through the Anglo-Maratha Wars.",
"marquee": false,
"id": "maratha-bichwa-scorpion-dagger" },

{ "name": "The Golden Throne of Maharaja Ranjit Singh",
"category": "Thrones & State Treasure",
"origin": "Lahore, Punjab",
"period": "c. 1820-1830",
"taken": "1849, annexation of Punjab",
"location": "Victoria and Albert Museum, London",
"status": "Still in Britain",
"image": "https://upload.wikimedia.org/wikipedia/commons/6/68/Ranjit_Singh%27s_golden_throne.jpg",
"summary": "A wood-and-resin throne sheathed entirely in sculpted gold, made for the 'Lion of Punjab'.",
"history": "Made by the goldsmith Hafez Muhammad Multani, it was catalogued as a war trophy the same year the Koh-i-Noor and the Golden Throne's own kingdom were absorbed into British India, and it has sat in a London museum ever since.",
"marquee": true,
"id": "the-golden-throne-of-maharaja-ranjit-singh" },

{ "name": "Seringapatam Palace Treasury",
"category": "Thrones & State Treasure",
"origin": "Seringapatam, Mysore",
"period": "Late 18th century",
"taken": "1799, fall of Seringapatam",
"location": "Dispersed, UK museums and private collections",
"status": "Still in Britain",
"image": "https://www.theheritagelab.in/wp-content/uploads/2022/12/Tipu-Cane.jpeg",
"summary": "The entire state treasure of Tipu Sultan's kingdom, formally auctioned among the victorious officers as legal spoils of war.",
"history": "There was no single museum to hold accountable — the treasury was simply divided up and carried away in pieces, which is exactly why so little of it has ever come back.",
"marquee": false,
"id": "seringapatam-palace-treasury" },

{  "name": "Ivory Throne of a Deccan Sultan",
"category": "Thrones & State Treasure",
"origin": "Deccan Sultanate",
"period": "17th century",
"taken": "Colonial-era acquisition",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://images.hindustantimes.com/rf/image_size_640x362/HT/p1/2014/02/18/Incoming/Pictures/1185506_Wallpaper2.jpg",
"summary": "A low ceremonial seat carved from ivory panels in the Deccan sultanate style.",
"history": "Ivory thrones of this kind were used for durbar audiences. Many left India through the private collections of Company officials stationed across the Deccan through the eighteenth and nineteenth centuries.",
"marquee": false,
 "id": "ivory-throne-of-a-deccan-sultan"
 },
{ "name": "Ceremonial Gaddi of a Rajput Court",
"category": "Thrones & State Treasure",
"origin": "Rajasthan",
"period": "18th-19th century",
"taken": "Colonial-era acquisition",
"location": "Museum storage, UK",
"status": "Still in Britain",
"image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6JlvZu4Jxf0COYbaeXDdHWacVsHh0Zjx9uG90ApURaTzDcX1GPHy-1cS_&s=10",
"summary": "A brocade-and-bolster gaddi, the true seat of sovereignty in Rajput states.",
"history": "A ruler was said to 'ascend the gaddi' rather than a throne. Several such ceremonial seats were removed from princely collections during and after the era of British paramountcy.",
"marquee": false,
"id": "ceremonial-gaddi-of-a-rajput-court" },

{ "name": "Silver Filigree Throne Chair, Cuttack Style",
"category": "Thrones & State Treasure",
"origin": "Odisha",
"period": "19th century",
"taken": "Colonial-era acquisition",
"location": "Private collection, UK",
"status": "Still in Britain",
"image": "https://i.pinimg.com/736x/2b/fb/07/2bfb07114bbcd07e2b22f1f78afd8e65.jpg",
"summary": "A finely worked silver filigree chair from Odisha's tarakasi craft tradition.",
"history": "Cuttack's filigree work was prized by colonial collectors as a showpiece of Indian craftsmanship, and whole furnishings were purchased or requisitioned for export to British exhibitions of Indian art.",
"marquee": false,
"id": "silver-filigree-throne-chair-cuttack-style" },

{
"name": "Howdah of a Mysore Noble",
"category": "Thrones & State Treasure",
"origin": "Mysore, Karnataka",
"period": "18th century",
"taken": "1799, fall of Seringapatam",
"location": "Clive Museum, Powis Castle, Wales",
"status": "Still in Britain",
"image": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Exhibit_in_Mysore_palace.jpg",
"summary": "A gilded ceremonial elephant-seat used in royal processions, taken from Tipu Sultan's Mysore.",
"history": "Processional equipment like this carried Mysore's rulers before their subjects. After Seringapatam fell, it was divided among British officers, much of it eventually settling in the Clive family collection.",
"marquee": false,
"id": "howdah-of-a-mysore-noble" },

{ "name": "Lahore Durbar State Records and Seals",
"category": "Thrones & State Treasure",
"origin": "Lahore, Punjab",
"period": "Early 19th century",
"taken": "1849",
"location": "British Library archives, UK",
"status": "Still in Britain",
"image": "https://assets-production.humap.site/yhlz8kjity5hy099bqa4nifqosf2?fit=crop&crop=faces%2Centropy%2Ccenter&w=1680",
"summary": "Administrative seals and court records of the Sikh Empire's Lahore Durbar.",
"history": "State papers and regalia were removed together when the Punjab administration was dissolved, becoming part of the colonial archive rather than remaining with any Indian successor institution.",
"marquee": false,
"id": "lahore-durbar-state-records-and-seals" },
  